/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppAccessControlRouteImport } from './routes/_app.access-control'
import { Route as AppAdvertisementsRouteImport } from './routes/_app.advertisements'
import { Route as AppAiRouteImport } from './routes/_app.ai'
import { Route as AppAiActivityRouteImport } from './routes/_app.ai-activity'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppApiRouteImport } from './routes/_app.api'
import { Route as AppArticlesRouteImport } from './routes/_app.articles'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppCategoriesRouteImport } from './routes/_app.categories'
import { Route as AppCommentsRouteImport } from './routes/_app.comments'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppFlagsRouteImport } from './routes/_app.flags'
import { Route as AppFollowersRouteImport } from './routes/_app.followers'
import { Route as AppHelpRouteImport } from './routes/_app.help'
import { Route as AppHighlightsRouteImport } from './routes/_app.highlights'
import { Route as AppJobsRouteImport } from './routes/_app.jobs'
import { Route as AppMediaRouteImport } from './routes/_app.media'
import { Route as AppModerationRouteImport } from './routes/_app.moderation'
import { Route as AppMusicRouteImport } from './routes/_app.music'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppPermissionsRouteImport } from './routes/_app.permissions'
import { Route as AppPlaylistsRouteImport } from './routes/_app.playlists'
import { Route as AppPostsRouteImport } from './routes/_app.posts'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppRequestAccessRouteImport } from './routes/_app.request-access'
import { Route as AppRoleRequestsRouteImport } from './routes/_app.role-requests'
import { Route as AppRolesRouteImport } from './routes/_app.roles'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppStatusRouteImport } from './routes/_app.status'
import { Route as AppStorageRouteImport } from './routes/_app.storage'
import { Route as AppTagsRouteImport } from './routes/_app.tags'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppVideosRouteImport } from './routes/_app.videos'
import { Route as AppWebhooksRouteImport } from './routes/_app.webhooks'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AppArticlesIndexRouteImport } from './routes/_app.articles.index'
import { Route as AppArticlesArticleIdRouteImport } from './routes/_app.articles.$articleId'
import { Route as AppAuditIndexRouteImport } from './routes/_app.audit.index'
import { Route as AppAuditEntryIdRouteImport } from './routes/_app.audit.$entryId'
import { Route as AppHelpArticleIdRouteImport } from './routes/_app.help.$articleId'
import { Route as AppModerationIndexRouteImport } from './routes/_app.moderation.index'
import { Route as AppModerationReportIdRouteImport } from './routes/_app.moderation.$reportId'
import { Route as AppSupportIndexRouteImport } from './routes/_app.support.index'
import { Route as AppSupportAgentsRouteImport } from './routes/_app.support.agents'
import { Route as AppSupportCannedResponsesRouteImport } from './routes/_app.support.canned-responses'
import { Route as AppSupportComparisonsRouteImport } from './routes/_app.support.comparisons'
import { Route as AppSupportKbRouteImport } from './routes/_app.support.kb'
import { Route as AppSupportReportsRouteImport } from './routes/_app.support.reports'
import { Route as AppSupportTicketsRouteImport } from './routes/_app.support.tickets'
import { Route as AppUsersIndexRouteImport } from './routes/_app.users.index'
import { Route as AppUsersUserIdRouteImport } from './routes/_app.users.$userId'
import { Route as AppUsersDeletedRouteImport } from './routes/_app.users.deleted'
import { Route as AppWebhooksIndexRouteImport } from './routes/_app.webhooks.index'
import { Route as AppWebhooksIdRouteImport } from './routes/_app.webhooks.$id'
import { Route as AppSupportAnalyticsIdRouteImport } from './routes/_app.support.analytics.$id'
import { Route as AppSupportDepartmentsIndexRouteImport } from './routes/_app.support.departments.index'
import { Route as AppSupportDepartmentsIdRouteImport } from './routes/_app.support.departments.$id'
import { Route as AppSupportTeamsIndexRouteImport } from './routes/_app.support.teams.index'
import { Route as AppSupportTeamsIdRouteImport } from './routes/_app.support.teams.$id'
import { Route as AppSupportTicketsIndexRouteImport } from './routes/_app.support.tickets.index'
import { Route as AppSupportTicketsTicketIdRouteImport } from './routes/_app.support.tickets.$ticketId'
import { Route as AppSupportTicketsAccessRequestsRouteImport } from './routes/_app.support.tickets.access-requests'
import { Route as AppSupportTicketsDeletedRouteImport } from './routes/_app.support.tickets.deleted'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAccessControlRoute = AppAccessControlRouteImport.update({
  id: '/access-control',
  path: '/access-control',
  getParentRoute: () => AppRoute,
} as any)
const AppAdvertisementsRoute = AppAdvertisementsRouteImport.update({
  id: '/advertisements',
  path: '/advertisements',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppAiActivityRoute = AppAiActivityRouteImport.update({
  id: '/ai-activity',
  path: '/ai-activity',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppApiRoute = AppApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AppRoute,
} as any)
const AppArticlesRoute = AppArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppCommentsRoute = AppCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppFlagsRoute = AppFlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => AppRoute,
} as any)
const AppFollowersRoute = AppFollowersRouteImport.update({
  id: '/followers',
  path: '/followers',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppHighlightsRoute = AppHighlightsRouteImport.update({
  id: '/highlights',
  path: '/highlights',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppMediaRoute = AppMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AppRoute,
} as any)
const AppModerationRoute = AppModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AppRoute,
} as any)
const AppMusicRoute = AppMusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppPermissionsRoute = AppPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaylistsRoute = AppPlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => AppRoute,
} as any)
const AppPostsRoute = AppPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestAccessRoute = AppRequestAccessRouteImport.update({
  id: '/request-access',
  path: '/request-access',
  getParentRoute: () => AppRoute,
} as any)
const AppRoleRequestsRoute = AppRoleRequestsRouteImport.update({
  id: '/role-requests',
  path: '/role-requests',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStatusRoute = AppStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => AppRoute,
} as any)
const AppStorageRoute = AppStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => AppRoute,
} as any)
const AppTagsRoute = AppTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppVideosRoute = AppVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AppRoute,
} as any)
const AppWebhooksRoute = AppWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AppRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppArticlesIndexRoute = AppArticlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppArticlesRoute,
} as any)
const AppArticlesArticleIdRoute = AppArticlesArticleIdRouteImport.update({
  id: '/$articleId',
  path: '/$articleId',
  getParentRoute: () => AppArticlesRoute,
} as any)
const AppAuditIndexRoute = AppAuditIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuditRoute,
} as any)
const AppAuditEntryIdRoute = AppAuditEntryIdRouteImport.update({
  id: '/$entryId',
  path: '/$entryId',
  getParentRoute: () => AppAuditRoute,
} as any)
const AppHelpArticleIdRoute = AppHelpArticleIdRouteImport.update({
  id: '/$articleId',
  path: '/$articleId',
  getParentRoute: () => AppHelpRoute,
} as any)
const AppModerationIndexRoute = AppModerationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppModerationRoute,
} as any)
const AppModerationReportIdRoute = AppModerationReportIdRouteImport.update({
  id: '/$reportId',
  path: '/$reportId',
  getParentRoute: () => AppModerationRoute,
} as any)
const AppSupportIndexRoute = AppSupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportAgentsRoute = AppSupportAgentsRouteImport.update({
  id: '/support/agents',
  path: '/support/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportCannedResponsesRoute =
  AppSupportCannedResponsesRouteImport.update({
    id: '/support/canned-responses',
    path: '/support/canned-responses',
    getParentRoute: () => AppRoute,
  } as any)
const AppSupportComparisonsRoute = AppSupportComparisonsRouteImport.update({
  id: '/support/comparisons',
  path: '/support/comparisons',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportKbRoute = AppSupportKbRouteImport.update({
  id: '/support/kb',
  path: '/support/kb',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportReportsRoute = AppSupportReportsRouteImport.update({
  id: '/support/reports',
  path: '/support/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportTicketsRoute = AppSupportTicketsRouteImport.update({
  id: '/support/tickets',
  path: '/support/tickets',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppUsersRoute,
} as any)
const AppUsersUserIdRoute = AppUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AppUsersRoute,
} as any)
const AppUsersDeletedRoute = AppUsersDeletedRouteImport.update({
  id: '/deleted',
  path: '/deleted',
  getParentRoute: () => AppUsersRoute,
} as any)
const AppWebhooksIndexRoute = AppWebhooksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWebhooksRoute,
} as any)
const AppWebhooksIdRoute = AppWebhooksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppWebhooksRoute,
} as any)
const AppSupportAnalyticsIdRoute = AppSupportAnalyticsIdRouteImport.update({
  id: '/support/analytics/$id',
  path: '/support/analytics/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportDepartmentsIndexRoute =
  AppSupportDepartmentsIndexRouteImport.update({
    id: '/support/departments/',
    path: '/support/departments/',
    getParentRoute: () => AppRoute,
  } as any)
const AppSupportDepartmentsIdRoute = AppSupportDepartmentsIdRouteImport.update({
  id: '/support/departments/$id',
  path: '/support/departments/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportTeamsIndexRoute = AppSupportTeamsIndexRouteImport.update({
  id: '/support/teams/',
  path: '/support/teams/',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportTeamsIdRoute = AppSupportTeamsIdRouteImport.update({
  id: '/support/teams/$id',
  path: '/support/teams/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportTicketsIndexRoute = AppSupportTicketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSupportTicketsRoute,
} as any)
const AppSupportTicketsTicketIdRoute =
  AppSupportTicketsTicketIdRouteImport.update({
    id: '/$ticketId',
    path: '/$ticketId',
    getParentRoute: () => AppSupportTicketsRoute,
  } as any)
const AppSupportTicketsAccessRequestsRoute =
  AppSupportTicketsAccessRequestsRouteImport.update({
    id: '/access-requests',
    path: '/access-requests',
    getParentRoute: () => AppSupportTicketsRoute,
  } as any)
const AppSupportTicketsDeletedRoute =
  AppSupportTicketsDeletedRouteImport.update({
    id: '/deleted',
    path: '/deleted',
    getParentRoute: () => AppSupportTicketsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-control': typeof AppAccessControlRoute
  '/advertisements': typeof AppAdvertisementsRoute
  '/ai': typeof AppAiRoute
  '/ai-activity': typeof AppAiActivityRoute
  '/analytics': typeof AppAnalyticsRoute
  '/api': typeof AppApiRoute
  '/articles': typeof AppArticlesRouteWithChildren
  '/audit': typeof AppAuditRouteWithChildren
  '/categories': typeof AppCategoriesRoute
  '/comments': typeof AppCommentsRoute
  '/dashboard': typeof AppDashboardRoute
  '/flags': typeof AppFlagsRoute
  '/followers': typeof AppFollowersRoute
  '/help': typeof AppHelpRouteWithChildren
  '/highlights': typeof AppHighlightsRoute
  '/jobs': typeof AppJobsRoute
  '/media': typeof AppMediaRoute
  '/moderation': typeof AppModerationRouteWithChildren
  '/music': typeof AppMusicRoute
  '/notifications': typeof AppNotificationsRoute
  '/permissions': typeof AppPermissionsRoute
  '/playlists': typeof AppPlaylistsRoute
  '/posts': typeof AppPostsRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/request-access': typeof AppRequestAccessRoute
  '/role-requests': typeof AppRoleRequestsRoute
  '/roles': typeof AppRolesRoute
  '/settings': typeof AppSettingsRoute
  '/status': typeof AppStatusRoute
  '/storage': typeof AppStorageRoute
  '/tags': typeof AppTagsRoute
  '/users': typeof AppUsersRouteWithChildren
  '/videos': typeof AppVideosRoute
  '/webhooks': typeof AppWebhooksRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/articles/$articleId': typeof AppArticlesArticleIdRoute
  '/audit/$entryId': typeof AppAuditEntryIdRoute
  '/help/$articleId': typeof AppHelpArticleIdRoute
  '/moderation/$reportId': typeof AppModerationReportIdRoute
  '/support/agents': typeof AppSupportAgentsRoute
  '/support/canned-responses': typeof AppSupportCannedResponsesRoute
  '/support/comparisons': typeof AppSupportComparisonsRoute
  '/support/kb': typeof AppSupportKbRoute
  '/support/reports': typeof AppSupportReportsRoute
  '/support/tickets': typeof AppSupportTicketsRouteWithChildren
  '/users/$userId': typeof AppUsersUserIdRoute
  '/users/deleted': typeof AppUsersDeletedRoute
  '/webhooks/$id': typeof AppWebhooksIdRoute
  '/articles/': typeof AppArticlesIndexRoute
  '/audit/': typeof AppAuditIndexRoute
  '/moderation/': typeof AppModerationIndexRoute
  '/support/': typeof AppSupportIndexRoute
  '/users/': typeof AppUsersIndexRoute
  '/webhooks/': typeof AppWebhooksIndexRoute
  '/support/analytics/$id': typeof AppSupportAnalyticsIdRoute
  '/support/departments/$id': typeof AppSupportDepartmentsIdRoute
  '/support/teams/$id': typeof AppSupportTeamsIdRoute
  '/support/tickets/$ticketId': typeof AppSupportTicketsTicketIdRoute
  '/support/tickets/access-requests': typeof AppSupportTicketsAccessRequestsRoute
  '/support/tickets/deleted': typeof AppSupportTicketsDeletedRoute
  '/support/departments/': typeof AppSupportDepartmentsIndexRoute
  '/support/teams/': typeof AppSupportTeamsIndexRoute
  '/support/tickets/': typeof AppSupportTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-control': typeof AppAccessControlRoute
  '/advertisements': typeof AppAdvertisementsRoute
  '/ai': typeof AppAiRoute
  '/ai-activity': typeof AppAiActivityRoute
  '/analytics': typeof AppAnalyticsRoute
  '/api': typeof AppApiRoute
  '/categories': typeof AppCategoriesRoute
  '/comments': typeof AppCommentsRoute
  '/dashboard': typeof AppDashboardRoute
  '/flags': typeof AppFlagsRoute
  '/followers': typeof AppFollowersRoute
  '/help': typeof AppHelpRouteWithChildren
  '/highlights': typeof AppHighlightsRoute
  '/jobs': typeof AppJobsRoute
  '/media': typeof AppMediaRoute
  '/music': typeof AppMusicRoute
  '/notifications': typeof AppNotificationsRoute
  '/permissions': typeof AppPermissionsRoute
  '/playlists': typeof AppPlaylistsRoute
  '/posts': typeof AppPostsRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/request-access': typeof AppRequestAccessRoute
  '/role-requests': typeof AppRoleRequestsRoute
  '/roles': typeof AppRolesRoute
  '/settings': typeof AppSettingsRoute
  '/status': typeof AppStatusRoute
  '/storage': typeof AppStorageRoute
  '/tags': typeof AppTagsRoute
  '/videos': typeof AppVideosRoute
  '/auth/login': typeof AuthLoginRoute
  '/articles/$articleId': typeof AppArticlesArticleIdRoute
  '/audit/$entryId': typeof AppAuditEntryIdRoute
  '/help/$articleId': typeof AppHelpArticleIdRoute
  '/moderation/$reportId': typeof AppModerationReportIdRoute
  '/support/agents': typeof AppSupportAgentsRoute
  '/support/canned-responses': typeof AppSupportCannedResponsesRoute
  '/support/comparisons': typeof AppSupportComparisonsRoute
  '/support/kb': typeof AppSupportKbRoute
  '/support/reports': typeof AppSupportReportsRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/users/deleted': typeof AppUsersDeletedRoute
  '/webhooks/$id': typeof AppWebhooksIdRoute
  '/articles': typeof AppArticlesIndexRoute
  '/audit': typeof AppAuditIndexRoute
  '/moderation': typeof AppModerationIndexRoute
  '/support': typeof AppSupportIndexRoute
  '/users': typeof AppUsersIndexRoute
  '/webhooks': typeof AppWebhooksIndexRoute
  '/support/analytics/$id': typeof AppSupportAnalyticsIdRoute
  '/support/departments/$id': typeof AppSupportDepartmentsIdRoute
  '/support/teams/$id': typeof AppSupportTeamsIdRoute
  '/support/tickets/$ticketId': typeof AppSupportTicketsTicketIdRoute
  '/support/tickets/access-requests': typeof AppSupportTicketsAccessRequestsRoute
  '/support/tickets/deleted': typeof AppSupportTicketsDeletedRoute
  '/support/departments': typeof AppSupportDepartmentsIndexRoute
  '/support/teams': typeof AppSupportTeamsIndexRoute
  '/support/tickets': typeof AppSupportTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/access-control': typeof AppAccessControlRoute
  '/_app/advertisements': typeof AppAdvertisementsRoute
  '/_app/ai': typeof AppAiRoute
  '/_app/ai-activity': typeof AppAiActivityRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/api': typeof AppApiRoute
  '/_app/articles': typeof AppArticlesRouteWithChildren
  '/_app/audit': typeof AppAuditRouteWithChildren
  '/_app/categories': typeof AppCategoriesRoute
  '/_app/comments': typeof AppCommentsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/flags': typeof AppFlagsRoute
  '/_app/followers': typeof AppFollowersRoute
  '/_app/help': typeof AppHelpRouteWithChildren
  '/_app/highlights': typeof AppHighlightsRoute
  '/_app/jobs': typeof AppJobsRoute
  '/_app/media': typeof AppMediaRoute
  '/_app/moderation': typeof AppModerationRouteWithChildren
  '/_app/music': typeof AppMusicRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/permissions': typeof AppPermissionsRoute
  '/_app/playlists': typeof AppPlaylistsRoute
  '/_app/posts': typeof AppPostsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/request-access': typeof AppRequestAccessRoute
  '/_app/role-requests': typeof AppRoleRequestsRoute
  '/_app/roles': typeof AppRolesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/status': typeof AppStatusRoute
  '/_app/storage': typeof AppStorageRoute
  '/_app/tags': typeof AppTagsRoute
  '/_app/users': typeof AppUsersRouteWithChildren
  '/_app/videos': typeof AppVideosRoute
  '/_app/webhooks': typeof AppWebhooksRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/_app/articles/$articleId': typeof AppArticlesArticleIdRoute
  '/_app/audit/$entryId': typeof AppAuditEntryIdRoute
  '/_app/help/$articleId': typeof AppHelpArticleIdRoute
  '/_app/moderation/$reportId': typeof AppModerationReportIdRoute
  '/_app/support/agents': typeof AppSupportAgentsRoute
  '/_app/support/canned-responses': typeof AppSupportCannedResponsesRoute
  '/_app/support/comparisons': typeof AppSupportComparisonsRoute
  '/_app/support/kb': typeof AppSupportKbRoute
  '/_app/support/reports': typeof AppSupportReportsRoute
  '/_app/support/tickets': typeof AppSupportTicketsRouteWithChildren
  '/_app/users/$userId': typeof AppUsersUserIdRoute
  '/_app/users/deleted': typeof AppUsersDeletedRoute
  '/_app/webhooks/$id': typeof AppWebhooksIdRoute
  '/_app/articles/': typeof AppArticlesIndexRoute
  '/_app/audit/': typeof AppAuditIndexRoute
  '/_app/moderation/': typeof AppModerationIndexRoute
  '/_app/support/': typeof AppSupportIndexRoute
  '/_app/users/': typeof AppUsersIndexRoute
  '/_app/webhooks/': typeof AppWebhooksIndexRoute
  '/_app/support/analytics/$id': typeof AppSupportAnalyticsIdRoute
  '/_app/support/departments/$id': typeof AppSupportDepartmentsIdRoute
  '/_app/support/teams/$id': typeof AppSupportTeamsIdRoute
  '/_app/support/tickets/$ticketId': typeof AppSupportTicketsTicketIdRoute
  '/_app/support/tickets/access-requests': typeof AppSupportTicketsAccessRequestsRoute
  '/_app/support/tickets/deleted': typeof AppSupportTicketsDeletedRoute
  '/_app/support/departments/': typeof AppSupportDepartmentsIndexRoute
  '/_app/support/teams/': typeof AppSupportTeamsIndexRoute
  '/_app/support/tickets/': typeof AppSupportTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-control'
    | '/advertisements'
    | '/ai'
    | '/ai-activity'
    | '/analytics'
    | '/api'
    | '/articles'
    | '/audit'
    | '/categories'
    | '/comments'
    | '/dashboard'
    | '/flags'
    | '/followers'
    | '/help'
    | '/highlights'
    | '/jobs'
    | '/media'
    | '/moderation'
    | '/music'
    | '/notifications'
    | '/permissions'
    | '/playlists'
    | '/posts'
    | '/profile'
    | '/reports'
    | '/request-access'
    | '/role-requests'
    | '/roles'
    | '/settings'
    | '/status'
    | '/storage'
    | '/tags'
    | '/users'
    | '/videos'
    | '/webhooks'
    | '/auth/login'
    | '/articles/$articleId'
    | '/audit/$entryId'
    | '/help/$articleId'
    | '/moderation/$reportId'
    | '/support/agents'
    | '/support/canned-responses'
    | '/support/comparisons'
    | '/support/kb'
    | '/support/reports'
    | '/support/tickets'
    | '/users/$userId'
    | '/users/deleted'
    | '/webhooks/$id'
    | '/articles/'
    | '/audit/'
    | '/moderation/'
    | '/support/'
    | '/users/'
    | '/webhooks/'
    | '/support/analytics/$id'
    | '/support/departments/$id'
    | '/support/teams/$id'
    | '/support/tickets/$ticketId'
    | '/support/tickets/access-requests'
    | '/support/tickets/deleted'
    | '/support/departments/'
    | '/support/teams/'
    | '/support/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-control'
    | '/advertisements'
    | '/ai'
    | '/ai-activity'
    | '/analytics'
    | '/api'
    | '/categories'
    | '/comments'
    | '/dashboard'
    | '/flags'
    | '/followers'
    | '/help'
    | '/highlights'
    | '/jobs'
    | '/media'
    | '/music'
    | '/notifications'
    | '/permissions'
    | '/playlists'
    | '/posts'
    | '/profile'
    | '/reports'
    | '/request-access'
    | '/role-requests'
    | '/roles'
    | '/settings'
    | '/status'
    | '/storage'
    | '/tags'
    | '/videos'
    | '/auth/login'
    | '/articles/$articleId'
    | '/audit/$entryId'
    | '/help/$articleId'
    | '/moderation/$reportId'
    | '/support/agents'
    | '/support/canned-responses'
    | '/support/comparisons'
    | '/support/kb'
    | '/support/reports'
    | '/users/$userId'
    | '/users/deleted'
    | '/webhooks/$id'
    | '/articles'
    | '/audit'
    | '/moderation'
    | '/support'
    | '/users'
    | '/webhooks'
    | '/support/analytics/$id'
    | '/support/departments/$id'
    | '/support/teams/$id'
    | '/support/tickets/$ticketId'
    | '/support/tickets/access-requests'
    | '/support/tickets/deleted'
    | '/support/departments'
    | '/support/teams'
    | '/support/tickets'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/access-control'
    | '/_app/advertisements'
    | '/_app/ai'
    | '/_app/ai-activity'
    | '/_app/analytics'
    | '/_app/api'
    | '/_app/articles'
    | '/_app/audit'
    | '/_app/categories'
    | '/_app/comments'
    | '/_app/dashboard'
    | '/_app/flags'
    | '/_app/followers'
    | '/_app/help'
    | '/_app/highlights'
    | '/_app/jobs'
    | '/_app/media'
    | '/_app/moderation'
    | '/_app/music'
    | '/_app/notifications'
    | '/_app/permissions'
    | '/_app/playlists'
    | '/_app/posts'
    | '/_app/profile'
    | '/_app/reports'
    | '/_app/request-access'
    | '/_app/role-requests'
    | '/_app/roles'
    | '/_app/settings'
    | '/_app/status'
    | '/_app/storage'
    | '/_app/tags'
    | '/_app/users'
    | '/_app/videos'
    | '/_app/webhooks'
    | '/auth/login'
    | '/_app/articles/$articleId'
    | '/_app/audit/$entryId'
    | '/_app/help/$articleId'
    | '/_app/moderation/$reportId'
    | '/_app/support/agents'
    | '/_app/support/canned-responses'
    | '/_app/support/comparisons'
    | '/_app/support/kb'
    | '/_app/support/reports'
    | '/_app/support/tickets'
    | '/_app/users/$userId'
    | '/_app/users/deleted'
    | '/_app/webhooks/$id'
    | '/_app/articles/'
    | '/_app/audit/'
    | '/_app/moderation/'
    | '/_app/support/'
    | '/_app/users/'
    | '/_app/webhooks/'
    | '/_app/support/analytics/$id'
    | '/_app/support/departments/$id'
    | '/_app/support/teams/$id'
    | '/_app/support/tickets/$ticketId'
    | '/_app/support/tickets/access-requests'
    | '/_app/support/tickets/deleted'
    | '/_app/support/departments/'
    | '/_app/support/teams/'
    | '/_app/support/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/access-control': {
      id: '/_app/access-control'
      path: '/access-control'
      fullPath: '/access-control'
      preLoaderRoute: typeof AppAccessControlRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/advertisements': {
      id: '/_app/advertisements'
      path: '/advertisements'
      fullPath: '/advertisements'
      preLoaderRoute: typeof AppAdvertisementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai': {
      id: '/_app/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-activity': {
      id: '/_app/ai-activity'
      path: '/ai-activity'
      fullPath: '/ai-activity'
      preLoaderRoute: typeof AppAiActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/api': {
      id: '/_app/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof AppApiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/articles': {
      id: '/_app/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof AppArticlesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/comments': {
      id: '/_app/comments'
      path: '/comments'
      fullPath: '/comments'
      preLoaderRoute: typeof AppCommentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/flags': {
      id: '/_app/flags'
      path: '/flags'
      fullPath: '/flags'
      preLoaderRoute: typeof AppFlagsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/followers': {
      id: '/_app/followers'
      path: '/followers'
      fullPath: '/followers'
      preLoaderRoute: typeof AppFollowersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help': {
      id: '/_app/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/highlights': {
      id: '/_app/highlights'
      path: '/highlights'
      fullPath: '/highlights'
      preLoaderRoute: typeof AppHighlightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/media': {
      id: '/_app/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AppMediaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/moderation': {
      id: '/_app/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof AppModerationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/music': {
      id: '/_app/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof AppMusicRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permissions': {
      id: '/_app/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AppPermissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/playlists': {
      id: '/_app/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof AppPlaylistsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/posts': {
      id: '/_app/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof AppPostsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/request-access': {
      id: '/_app/request-access'
      path: '/request-access'
      fullPath: '/request-access'
      preLoaderRoute: typeof AppRequestAccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/role-requests': {
      id: '/_app/role-requests'
      path: '/role-requests'
      fullPath: '/role-requests'
      preLoaderRoute: typeof AppRoleRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles': {
      id: '/_app/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/status': {
      id: '/_app/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof AppStatusRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/storage': {
      id: '/_app/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof AppStorageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tags': {
      id: '/_app/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof AppTagsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/videos': {
      id: '/_app/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof AppVideosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/webhooks': {
      id: '/_app/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof AppWebhooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/articles/': {
      id: '/_app/articles/'
      path: '/'
      fullPath: '/articles/'
      preLoaderRoute: typeof AppArticlesIndexRouteImport
      parentRoute: typeof AppArticlesRoute
    }
    '/_app/articles/$articleId': {
      id: '/_app/articles/$articleId'
      path: '/$articleId'
      fullPath: '/articles/$articleId'
      preLoaderRoute: typeof AppArticlesArticleIdRouteImport
      parentRoute: typeof AppArticlesRoute
    }
    '/_app/audit/': {
      id: '/_app/audit/'
      path: '/'
      fullPath: '/audit/'
      preLoaderRoute: typeof AppAuditIndexRouteImport
      parentRoute: typeof AppAuditRoute
    }
    '/_app/audit/$entryId': {
      id: '/_app/audit/$entryId'
      path: '/$entryId'
      fullPath: '/audit/$entryId'
      preLoaderRoute: typeof AppAuditEntryIdRouteImport
      parentRoute: typeof AppAuditRoute
    }
    '/_app/help/$articleId': {
      id: '/_app/help/$articleId'
      path: '/$articleId'
      fullPath: '/help/$articleId'
      preLoaderRoute: typeof AppHelpArticleIdRouteImport
      parentRoute: typeof AppHelpRoute
    }
    '/_app/moderation/': {
      id: '/_app/moderation/'
      path: '/'
      fullPath: '/moderation/'
      preLoaderRoute: typeof AppModerationIndexRouteImport
      parentRoute: typeof AppModerationRoute
    }
    '/_app/moderation/$reportId': {
      id: '/_app/moderation/$reportId'
      path: '/$reportId'
      fullPath: '/moderation/$reportId'
      preLoaderRoute: typeof AppModerationReportIdRouteImport
      parentRoute: typeof AppModerationRoute
    }
    '/_app/support/': {
      id: '/_app/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof AppSupportIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support/agents': {
      id: '/_app/support/agents'
      path: '/support/agents'
      fullPath: '/support/agents'
      preLoaderRoute: typeof AppSupportAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support/canned-responses': {
      id: '/_app/support/canned-responses'
      path: '/support/canned-responses'
      fullPath: '/support/canned-responses'
      preLoaderRoute: typeof AppSupportCannedResponsesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support/comparisons': {
      id: '/_app/support/comparisons'
      path: '/support/comparisons'
      fullPath: '/support/comparisons'
      preLoaderRoute: typeof AppSupportComparisonsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support/kb': {
      id: '/_app/support/kb'
      path: '/support/kb'
      fullPath: '/support/kb'
      preLoaderRoute: typeof AppSupportKbRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support/reports': {
      id: '/_app/support/reports'
      path: '/support/reports'
      fullPath: '/support/reports'
      preLoaderRoute: typeof AppSupportReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support/tickets': {
      id: '/_app/support/tickets'
      path: '/support/tickets'
      fullPath: '/support/tickets'
      preLoaderRoute: typeof AppSupportTicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/': {
      id: '/_app/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppUsersRoute
    }
    '/_app/users/$userId': {
      id: '/_app/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AppUsersUserIdRouteImport
      parentRoute: typeof AppUsersRoute
    }
    '/_app/users/deleted': {
      id: '/_app/users/deleted'
      path: '/deleted'
      fullPath: '/users/deleted'
      preLoaderRoute: typeof AppUsersDeletedRouteImport
      parentRoute: typeof AppUsersRoute
    }
    '/_app/webhooks/': {
      id: '/_app/webhooks/'
      path: '/'
      fullPath: '/webhooks/'
      preLoaderRoute: typeof AppWebhooksIndexRouteImport
      parentRoute: typeof AppWebhooksRoute
    }
    '/_app/webhooks/$id': {
      id: '/_app/webhooks/$id'
      path: '/$id'
      fullPath: '/webhooks/$id'
      preLoaderRoute: typeof AppWebhooksIdRouteImport
      parentRoute: typeof AppWebhooksRoute
    }
    '/_app/support/analytics/$id': {
      id: '/_app/support/analytics/$id'
      path: '/support/analytics/$id'
      fullPath: '/support/analytics/$id'
      preLoaderRoute: typeof AppSupportAnalyticsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support/departments/': {
      id: '/_app/support/departments/'
      path: '/support/departments'
      fullPath: '/support/departments/'
      preLoaderRoute: typeof AppSupportDepartmentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support/departments/$id': {
      id: '/_app/support/departments/$id'
      path: '/support/departments/$id'
      fullPath: '/support/departments/$id'
      preLoaderRoute: typeof AppSupportDepartmentsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support/teams/': {
      id: '/_app/support/teams/'
      path: '/support/teams'
      fullPath: '/support/teams/'
      preLoaderRoute: typeof AppSupportTeamsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support/teams/$id': {
      id: '/_app/support/teams/$id'
      path: '/support/teams/$id'
      fullPath: '/support/teams/$id'
      preLoaderRoute: typeof AppSupportTeamsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support/tickets/': {
      id: '/_app/support/tickets/'
      path: '/'
      fullPath: '/support/tickets/'
      preLoaderRoute: typeof AppSupportTicketsIndexRouteImport
      parentRoute: typeof AppSupportTicketsRoute
    }
    '/_app/support/tickets/$ticketId': {
      id: '/_app/support/tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/support/tickets/$ticketId'
      preLoaderRoute: typeof AppSupportTicketsTicketIdRouteImport
      parentRoute: typeof AppSupportTicketsRoute
    }
    '/_app/support/tickets/access-requests': {
      id: '/_app/support/tickets/access-requests'
      path: '/access-requests'
      fullPath: '/support/tickets/access-requests'
      preLoaderRoute: typeof AppSupportTicketsAccessRequestsRouteImport
      parentRoute: typeof AppSupportTicketsRoute
    }
    '/_app/support/tickets/deleted': {
      id: '/_app/support/tickets/deleted'
      path: '/deleted'
      fullPath: '/support/tickets/deleted'
      preLoaderRoute: typeof AppSupportTicketsDeletedRouteImport
      parentRoute: typeof AppSupportTicketsRoute
    }
  }
}

interface AppArticlesRouteChildren {
  AppArticlesArticleIdRoute: typeof AppArticlesArticleIdRoute
  AppArticlesIndexRoute: typeof AppArticlesIndexRoute
}

const AppArticlesRouteChildren: AppArticlesRouteChildren = {
  AppArticlesArticleIdRoute: AppArticlesArticleIdRoute,
  AppArticlesIndexRoute: AppArticlesIndexRoute,
}

const AppArticlesRouteWithChildren = AppArticlesRoute._addFileChildren(
  AppArticlesRouteChildren,
)

interface AppAuditRouteChildren {
  AppAuditEntryIdRoute: typeof AppAuditEntryIdRoute
  AppAuditIndexRoute: typeof AppAuditIndexRoute
}

const AppAuditRouteChildren: AppAuditRouteChildren = {
  AppAuditEntryIdRoute: AppAuditEntryIdRoute,
  AppAuditIndexRoute: AppAuditIndexRoute,
}

const AppAuditRouteWithChildren = AppAuditRoute._addFileChildren(
  AppAuditRouteChildren,
)

interface AppHelpRouteChildren {
  AppHelpArticleIdRoute: typeof AppHelpArticleIdRoute
}

const AppHelpRouteChildren: AppHelpRouteChildren = {
  AppHelpArticleIdRoute: AppHelpArticleIdRoute,
}

const AppHelpRouteWithChildren =
  AppHelpRoute._addFileChildren(AppHelpRouteChildren)

interface AppModerationRouteChildren {
  AppModerationReportIdRoute: typeof AppModerationReportIdRoute
  AppModerationIndexRoute: typeof AppModerationIndexRoute
}

const AppModerationRouteChildren: AppModerationRouteChildren = {
  AppModerationReportIdRoute: AppModerationReportIdRoute,
  AppModerationIndexRoute: AppModerationIndexRoute,
}

const AppModerationRouteWithChildren = AppModerationRoute._addFileChildren(
  AppModerationRouteChildren,
)

interface AppUsersRouteChildren {
  AppUsersUserIdRoute: typeof AppUsersUserIdRoute
  AppUsersDeletedRoute: typeof AppUsersDeletedRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
}

const AppUsersRouteChildren: AppUsersRouteChildren = {
  AppUsersUserIdRoute: AppUsersUserIdRoute,
  AppUsersDeletedRoute: AppUsersDeletedRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
}

const AppUsersRouteWithChildren = AppUsersRoute._addFileChildren(
  AppUsersRouteChildren,
)

interface AppWebhooksRouteChildren {
  AppWebhooksIdRoute: typeof AppWebhooksIdRoute
  AppWebhooksIndexRoute: typeof AppWebhooksIndexRoute
}

const AppWebhooksRouteChildren: AppWebhooksRouteChildren = {
  AppWebhooksIdRoute: AppWebhooksIdRoute,
  AppWebhooksIndexRoute: AppWebhooksIndexRoute,
}

const AppWebhooksRouteWithChildren = AppWebhooksRoute._addFileChildren(
  AppWebhooksRouteChildren,
)

interface AppSupportTicketsRouteChildren {
  AppSupportTicketsTicketIdRoute: typeof AppSupportTicketsTicketIdRoute
  AppSupportTicketsAccessRequestsRoute: typeof AppSupportTicketsAccessRequestsRoute
  AppSupportTicketsDeletedRoute: typeof AppSupportTicketsDeletedRoute
  AppSupportTicketsIndexRoute: typeof AppSupportTicketsIndexRoute
}

const AppSupportTicketsRouteChildren: AppSupportTicketsRouteChildren = {
  AppSupportTicketsTicketIdRoute: AppSupportTicketsTicketIdRoute,
  AppSupportTicketsAccessRequestsRoute: AppSupportTicketsAccessRequestsRoute,
  AppSupportTicketsDeletedRoute: AppSupportTicketsDeletedRoute,
  AppSupportTicketsIndexRoute: AppSupportTicketsIndexRoute,
}

const AppSupportTicketsRouteWithChildren =
  AppSupportTicketsRoute._addFileChildren(AppSupportTicketsRouteChildren)

interface AppRouteChildren {
  AppAccessControlRoute: typeof AppAccessControlRoute
  AppAdvertisementsRoute: typeof AppAdvertisementsRoute
  AppAiRoute: typeof AppAiRoute
  AppAiActivityRoute: typeof AppAiActivityRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppApiRoute: typeof AppApiRoute
  AppArticlesRoute: typeof AppArticlesRouteWithChildren
  AppAuditRoute: typeof AppAuditRouteWithChildren
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppCommentsRoute: typeof AppCommentsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFlagsRoute: typeof AppFlagsRoute
  AppFollowersRoute: typeof AppFollowersRoute
  AppHelpRoute: typeof AppHelpRouteWithChildren
  AppHighlightsRoute: typeof AppHighlightsRoute
  AppJobsRoute: typeof AppJobsRoute
  AppMediaRoute: typeof AppMediaRoute
  AppModerationRoute: typeof AppModerationRouteWithChildren
  AppMusicRoute: typeof AppMusicRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPermissionsRoute: typeof AppPermissionsRoute
  AppPlaylistsRoute: typeof AppPlaylistsRoute
  AppPostsRoute: typeof AppPostsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRequestAccessRoute: typeof AppRequestAccessRoute
  AppRoleRequestsRoute: typeof AppRoleRequestsRoute
  AppRolesRoute: typeof AppRolesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStatusRoute: typeof AppStatusRoute
  AppStorageRoute: typeof AppStorageRoute
  AppTagsRoute: typeof AppTagsRoute
  AppUsersRoute: typeof AppUsersRouteWithChildren
  AppVideosRoute: typeof AppVideosRoute
  AppWebhooksRoute: typeof AppWebhooksRouteWithChildren
  AppSupportAgentsRoute: typeof AppSupportAgentsRoute
  AppSupportCannedResponsesRoute: typeof AppSupportCannedResponsesRoute
  AppSupportComparisonsRoute: typeof AppSupportComparisonsRoute
  AppSupportKbRoute: typeof AppSupportKbRoute
  AppSupportReportsRoute: typeof AppSupportReportsRoute
  AppSupportTicketsRoute: typeof AppSupportTicketsRouteWithChildren
  AppSupportIndexRoute: typeof AppSupportIndexRoute
  AppSupportAnalyticsIdRoute: typeof AppSupportAnalyticsIdRoute
  AppSupportDepartmentsIdRoute: typeof AppSupportDepartmentsIdRoute
  AppSupportTeamsIdRoute: typeof AppSupportTeamsIdRoute
  AppSupportDepartmentsIndexRoute: typeof AppSupportDepartmentsIndexRoute
  AppSupportTeamsIndexRoute: typeof AppSupportTeamsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccessControlRoute: AppAccessControlRoute,
  AppAdvertisementsRoute: AppAdvertisementsRoute,
  AppAiRoute: AppAiRoute,
  AppAiActivityRoute: AppAiActivityRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppApiRoute: AppApiRoute,
  AppArticlesRoute: AppArticlesRouteWithChildren,
  AppAuditRoute: AppAuditRouteWithChildren,
  AppCategoriesRoute: AppCategoriesRoute,
  AppCommentsRoute: AppCommentsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFlagsRoute: AppFlagsRoute,
  AppFollowersRoute: AppFollowersRoute,
  AppHelpRoute: AppHelpRouteWithChildren,
  AppHighlightsRoute: AppHighlightsRoute,
  AppJobsRoute: AppJobsRoute,
  AppMediaRoute: AppMediaRoute,
  AppModerationRoute: AppModerationRouteWithChildren,
  AppMusicRoute: AppMusicRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPermissionsRoute: AppPermissionsRoute,
  AppPlaylistsRoute: AppPlaylistsRoute,
  AppPostsRoute: AppPostsRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppRequestAccessRoute: AppRequestAccessRoute,
  AppRoleRequestsRoute: AppRoleRequestsRoute,
  AppRolesRoute: AppRolesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStatusRoute: AppStatusRoute,
  AppStorageRoute: AppStorageRoute,
  AppTagsRoute: AppTagsRoute,
  AppUsersRoute: AppUsersRouteWithChildren,
  AppVideosRoute: AppVideosRoute,
  AppWebhooksRoute: AppWebhooksRouteWithChildren,
  AppSupportAgentsRoute: AppSupportAgentsRoute,
  AppSupportCannedResponsesRoute: AppSupportCannedResponsesRoute,
  AppSupportComparisonsRoute: AppSupportComparisonsRoute,
  AppSupportKbRoute: AppSupportKbRoute,
  AppSupportReportsRoute: AppSupportReportsRoute,
  AppSupportTicketsRoute: AppSupportTicketsRouteWithChildren,
  AppSupportIndexRoute: AppSupportIndexRoute,
  AppSupportAnalyticsIdRoute: AppSupportAnalyticsIdRoute,
  AppSupportDepartmentsIdRoute: AppSupportDepartmentsIdRoute,
  AppSupportTeamsIdRoute: AppSupportTeamsIdRoute,
  AppSupportDepartmentsIndexRoute: AppSupportDepartmentsIndexRoute,
  AppSupportTeamsIndexRoute: AppSupportTeamsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
