// Auto-generated by scripts/split-dictionaries.py. Do not edit by hand.

import { NamespaceDict, LocaleTag } from "../types";

import { EN_DICT } from "./base.en";
import { FR_DICT } from "./base.fr";
import { ES_DICT } from "./base.es";
import { DE_DICT } from "./base.de";
import { IT_DICT } from "./base.it";
import { PT_DICT } from "./base.pt";
import { NL_DICT } from "./base.nl";
import { SV_DICT } from "./base.sv";
import { DA_DICT } from "./base.da";
import { FI_DICT } from "./base.fi";
import { NO_DICT } from "./base.no";
import { PL_DICT } from "./base.pl";
import { CS_DICT } from "./base.cs";
import { HU_DICT } from "./base.hu";
import { RO_DICT } from "./base.ro";
import { BG_DICT } from "./base.bg";
import { UK_DICT } from "./base.uk";
import { EL_DICT } from "./base.el";
import { AR_DICT } from "./base.ar";
import { HE_DICT } from "./base.he";
import { FA_DICT } from "./base.fa";
import { TR_DICT } from "./base.tr";
import { HI_DICT } from "./base.hi";
import { ID_DICT } from "./base.id";
import { MS_DICT } from "./base.ms";
import { TH_DICT } from "./base.th";
import { ZH_DICT } from "./base.zh";
import { JA_DICT } from "./base.ja";
import { KO_DICT } from "./base.ko";
import { VI_DICT } from "./base.vi";
import { RU_DICT } from "./base.ru";

export const DICTIONARIES: Record<LocaleTag, NamespaceDict> = {
  en: EN_DICT,
  fr: FR_DICT,
  es: ES_DICT,
  de: DE_DICT,
  it: IT_DICT,
  pt: PT_DICT,
  nl: NL_DICT,
  sv: SV_DICT,
  da: DA_DICT,
  fi: FI_DICT,
  no: NO_DICT,
  pl: PL_DICT,
  cs: CS_DICT,
  hu: HU_DICT,
  ro: RO_DICT,
  bg: BG_DICT,
  uk: UK_DICT,
  el: EL_DICT,
  ar: AR_DICT,
  he: HE_DICT,
  fa: FA_DICT,
  tr: TR_DICT,
  hi: HI_DICT,
  id: ID_DICT,
  ms: MS_DICT,
  th: TH_DICT,
  zh: ZH_DICT,
  ja: JA_DICT,
  ko: KO_DICT,
  vi: VI_DICT,
  ru: RU_DICT,
};

export {
  EN_DICT,
  FR_DICT,
  ES_DICT,
  DE_DICT,
  IT_DICT,
  PT_DICT,
  NL_DICT,
  SV_DICT,
  DA_DICT,
  FI_DICT,
  NO_DICT,
  PL_DICT,
  CS_DICT,
  HU_DICT,
  RO_DICT,
  BG_DICT,
  UK_DICT,
  EL_DICT,
  AR_DICT,
  HE_DICT,
  FA_DICT,
  TR_DICT,
  HI_DICT,
  ID_DICT,
  MS_DICT,
  TH_DICT,
  ZH_DICT,
  JA_DICT,
  KO_DICT,
  VI_DICT,
  RU_DICT,
};
