name: DeployAPI

on:
  push:
    branches:
      - main
    paths:
      - 'packages/api/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: packages/api/package.json
      - run: cd packages/api && npm ci
      - run: cd packages/api && npx prisma generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - run: cd packages/api && npm run build
      - run: cd packages/api && npx prisma migrate deploy
        if: github.ref == 'refs/heads/main'
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
